name: Master

on:
  push:
    branches: [ master ]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run assemble
      run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.5.0

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: run detektCheck
      run: ./gradlew detektCheck
